# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

from snakemake.io import glob_wildcards, expand

EXTRACT_TO = ["sh_qiime_release_10.05.2021",
            "sh_qiime_release_s_10.05.2021",
            "sh_qiime_release_all_10.05.2021",
            "sh_qiime_release_s_all_10.05.2021"
            ]

# SAMPLES = expand("{folder}", folder=EXTRACT_TO)
# print(SAMPLES)

rule all:
    input:
        expand("results/{folder}", folder=EXTRACT_TO)

rule download: # This is not proper snakemake. I can't get my tuples to work.
    output:
        directory("results/{folder}")
    # conda: # TODO: troubleshoot this and pin wget and tar versions
    #      "envs/unix.yaml"
    shell:
        """
        # 8.3	2021-05-10	Fungi	14 097	44 343	Current	https://doi.org/10.15156/BIO/1264708
        wget -qO- https://files.plutof.ut.ee/public/orig/C5/54/C5547B97AAA979E45F79DC4C8C4B12113389343D7588716B5AD330F8BDB300C9.tgz | tar xz -C results # sh_qiime_release_10.05.2021       # normal
        # 8.3	2021-05-10	Fungi	14 097	83 993	Current	https://doi.org/10.15156/BIO/1264763
        wget -qO- https://files.plutof.ut.ee/public/orig/B3/05/B3054DF783AC61A0C3BD0FDEB0516EC394934809AAE43CA0F3081C0A184FAA39.tgz | tar xz -C results # sh_qiime_release_s_10.05.2021     # add s for 97% singletons
        # 8.3	2021-05-10	All eukaryotes	14 237	96 423	Current	https://doi.org/10.15156/BIO/1264819
        wget -qO- https://files.plutof.ut.ee/public/orig/48/29/4829D91F763E20F0F4376A60AA53FC9FBE6029A7D1BDC1B45347DD64EDE5D560.tgz | tar xz -C results # sh_qiime_release_all_10.05.2021   # add all for Euks
        # 8.3	2021-05-10	All eukaryotes	14 237	190 888	Current	https://doi.org/10.15156/BIO/1264861
        wget -qO- https://files.plutof.ut.ee/public/orig/1D/31/1D31FA3A308BDC2FB2750D62C0AA40C5058C15405A3CC5C626CC3A3F5E3903ED.tgz | tar xz -C results # sh_qiime_release_s_all_10.05.2021 # and s and all for 07% Euks singletons
        """
