---
title: "GitHub Release Stats"
author: "Colin J. Brislawn"
date: "Feb 3, 2026"
output: html_document
---

```{r setup0, include=FALSE}
library("tidyverse")
library("rvest")
library("viridisLite")

# library("kableExtra")
# library("vroom")

knitr::opts_chunk$set(echo = TRUE, cache = FALSE)

theme_set(theme_bw())
theme_update(
  strip.background = element_blank(),
  axis.text.x = element_text(angle = 0, hjust = 0.5)
)
```

```{r lint, include=F, eval=F}
library(styler)
# styler:::style_active_file()
style_file("Release-stats.Rmd", strict = TRUE)

# library(lintr)
# lintr::lint("Release-stats.Rmd",
#   linters = linters_with_defaults(
#     line_length_linter = line_length_linter(120),
#     object_name_linter = NULL,
#     commented_code_linter = NULL
#   )
# )
```

```{r}
# rvest does not work here because it can't run the javascript
# So we use a third party tool
# https://github.com/kefir500/github-release-stats

# Install like https://stackoverflow.com/a/39981888
# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
# nvm install node
# npm i -g github-release-stats
# Run
# ghstats colinbrislawn unite-train -d > release.txt

release_text <- read_lines("release.txt") %>%
  paste(collapse = "\n") %>%
  str_split("\nName: ") %>%
  .[[1]] %>%
  tail(-1)

release_data <- tibble(release_text) %>%
  mutate(
    Name = str_extract(release_text, "Name: (.*)"),
    Tag = str_extract(release_text, "Tag: (.*)"),
    URL = str_extract(release_text, "URL: (.*)"),
    Published_at = str_extract(release_text, "Published at: (.*)"),
    Total_downloads = as.numeric(str_extract(release_text, "(\\d+) total downloads")),
    Assets = str_extract(release_text, "Assets:\\n(.*\n)+") %>% str_trim()
  ) %>%
  select(-release_text) %>%
  mutate(Assets = map(Assets, function(assets_text) {
    if (is.na(assets_text)) {
      return(tibble(asset = character(), downloads = numeric()))
    }
    assets_text %>%
      str_split("\n") %>%
      .[[1]] %>%
      str_trim() %>%
      str_match("(.*) - (\\d+) download\\(s\\)") %>%
      as_tibble(.name_repair = "universal") %>%
      select(asset = ...2, downloads = ...3) %>%
      mutate(downloads = as.numeric(downloads))
  })) %>%
  unnest(Assets)

# release_data
```

```{r, fig.height=4}
release_data2 <- release_data |>
  mutate(Tag = Tag |>
    str_remove("-demo") |>
    str_remove("Tag: ")) |>
  extract(Tag, c("UNITE", "QIIME2_Version"), regex = "(.*)-qiime2-(20.*)") |>
  separate(UNITE, c("unite_version", "unite_date"), sep = "-") |>
  separate(QIIME2_Version, c("q2year", "q2month"), remove = FALSE) |>
  mutate(
    unite_version = unite_version |> str_remove("^v") |> as.numeric() |> as_factor(),
    q2month = factor(q2month, levels = sort(unique(as.integer(q2month))))
  )

# release_data2 |>
#   select(unite_version, unite_date) |>
#   distinct()
# release_data2 |>
#   select(UNITE_Version, unite_date) |>
#   table()

release_data2 |>
  ggplot(aes(q2month, downloads, fill = unite_version)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_viridis_d(begin = 0.2, end = 0.6) +
  facet_grid(~q2year, scales = "free", space = "free") +
  labs(title = "Downloads over time")
ggsave("downloads_time.png", height = 4)
```

```{r, fig.height=4}
release_data3 <- release_data2 %>%
  separate(asset, c("u", "u_v", "id", "s1", "s2", "s3"), sep = "_", remove = FALSE) |>
  filter(!is.na(u_v)) |>
  mutate(
    singletons = case_when(
      s1 == "s" ~ "Singletons",
      TRUE ~ "No Singletons "
    ),
    scope = case_when(
      s1 == "all" | s2 == "all" ~ "all Euks",
      TRUE ~ "only Fungi"
    )
  )

# release_data3 |>
#   ggplot(aes(id, downloads, color = id)) +
#   geom_boxplot() +
#   geom_jitter(height = 0, width = 0.1) +
#   # facet_grid(singletons~scope) +
#   scale_y_log10(breaks = c(1, 10, 100, 1000)) +
#   labs(title = "Downloads per ID")
# ggsave("downloads_id.png")

# release_data3 |>
#   ggplot(aes(scope, downloads, color = id)) +
#   geom_boxplot() +
#   # facet_grid(singletons~scope) +
#   scale_y_log10(breaks = c(1, 10, 100, 1000)) +
#   labs(title = "Downloads per taxa scope")
# ggsave("downloads_scope.png")

# release_data3 |>
#   ggplot(aes(singletons, downloads, color = id)) +
#   geom_boxplot() +
#   # facet_grid(singletons~scope) +
#   scale_y_log10(breaks = c(1, 10, 100, 1000)) +
#   labs(title = "Downloads with Singletons")
# ggsave("downloads_singletons.png")

release_data3 |>
  ggplot(aes(id, downloads, color = id)) +
  geom_boxplot() +
  geom_jitter(height = 0, width = 0) +
  facet_grid(~ singletons + scope) +
  scale_y_log10(breaks = c(1, 10, 100, 1000))
ggsave("downloads_types.png", height = 4)
```

```{r, include=F, eval=F}
rmarkdown::render("Release-stats.Rmd")
```
